---
- import_playbook: system_update.yml
- import_playbook: ssh_setup.yml
- import_playbook: system_update.yml
- import_playbook: command-line-utils_install.yml
- import_playbook: neovim_install.yml
- import_playbook: nvm_install.yml
- import_playbook: python3_install.yml
- import_playbook: dotfiles_clone.yml
