- hosts: all
  become: true
  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: Install Oh My Zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
